# Generated by Django 4.2.2 on 2023-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=150)),
                ('artiste', models.CharField(max_length=200)),
                ('music_file', models.FileField(upload_to='media/music')),
                ('cover_image', models.ImageField(upload_to='media/images')),
                ('time_length', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
